language: node_js

sudo: false
dist: trusty

git:
  depth: 3

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

notifications:
  email: false
  slack:
    secure: qorwdTu1od1QSvbwiR1JX60czaUpPFgTacBr0WgX+KJaLABjkc3+2j+rYVpbZu8Gwb5zU+IEApp8QSySRkETubqMTou7AFAVwbgvf3xBcj0/9KgKJLmHkD102CzfqMo6Aq7KCtzhBpzMmAPmp7MxEv3vhSNDUsOKcGXO0RdT4qzOhfHo6xQ9daxUyoQxaDMOsPZSm9hiuXWzFdgD/IleEzpls3NBCR1S4xBVmppaRvLppbmW9oaM2LoJ9rbr0MvJnF2gRXK7hUjoX9G7t0N4FwsNhKpIFeAyhiIicIKVQFdDLNbRdwaUZ5z8LpjjAEUr4lbruXfPIOKcFpsAmeOn7Pw67WNp6NwLwd1s4fH7OjM8cqqfpJue01t4m6fLxsTq4KZA+NRn4bSEnijBSR435XFfkT391AQ+N/mWjQidoLvR4fadzq5wyvGXJ0TacIGkampjWuqNQupTVDdndFZbvQLC0dpRXJRb0KdIxi4a3blaFTclO76Ds2hVh8wM8Z+v3uFaBOkAg5W1HyvIZ6IPwUSG4X1q04q8jJjAkuMmmDBvuIgz2aKieCmIIwTMo9GP4mVmfK+4QB8aLu++kTQDFn4QfOFCsmFej4m8q8BIaywVl74AzS2LAqaRZtTAzKm4uJ6rrTGs/b4cyOYHanNUNMZkzWq2aVIgH3HUvhYg8OQ=

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"

cache:
  directories:
    - "${HOME}/.composer/cache"
    - "${TRAVIS_BUILD_DIR}/.work/cache"

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: test
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: deploy
    if: tag IS present

before_script:
  - bash bin/prepare.sh

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash bin/check/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash bin/check/phpmd.sh

    - stage: test
      language: php
      php: '7.1'
      script: bash bin/test/phpunit.sh
    - stage: test
      language: php
      php: '7.2'
      script: bash bin/test/phpunit.sh
    - stage: test
      language: php
      php: '7.3'
      script: bash bin/test/phpunit.sh

    - stage: deploy
      language: php
      php: '7.2'
      script: skip
      before_deploy:
        - source bin/deploy/env.sh
        - bash bin/deploy/create-zip.sh
      deploy:
        provider: releases
        skip_cleanup: true
        name: ${RELEASE_TITLE}
        tag_name: ${RELEASE_TAG}
        file: ${RELEASE_FILE}
        body: ${RELEASE_BODY}
        api_key:
          secure: JOMSKXSTGPeWirfKE6mv4fpTMo+FVSdoMS3ARyBzmPbbqZp/+dPojhwr4SW1IMUrVcy0s4sUpBs2iMzfIV7QC/71gmXRALF7RZ0W8fslVOCCCdclhZHF/k+puuPIZEeSglPnRWgc5tWOIqA3N4yGOUf9ib1o2Irelhrsa2jfZaLFqNDjpqU9ZD5FwnVLQZPWXFVfHjvPOpO2aBE83z3Bf2yrpL1wDqufD+T0ZYN2D8Gjp+/zVp1p3XepFXzthok+j5iIHrrHXMeFUOb8t7N23w88bfq8Do1bocNv1URGRyS7XC04Vhcn5yKuaRYSuA5nM8DRd+23tJSSTUm9R8Gjmdz+GPE7epBcgPC+hxYPoKMbIL/TWrF9coDSV/pLAWPyAPsuu3tgwrte9txu++XX6YNSxn6hTKW/6vASY2KjMRy8uPllDFU5GkoSHl3pxY3CZ1Dby1aKdIjh7ONHpLqQ1cS41FocYzj+1GenlUns/Y3lr2OtmkQO8eewl8MRA3giiKXWYUcxC8lT7Hs6FoGcf8ht3W3s1A28GM6LCsO6h2Lbj2YfkTmsoJbQEPuAVJ7DIa/jo71JO0Q6Eo7cFAy3tRAhIW2KK7MeJ95sj+MHPElnI+vJVHOVJgmWQ8a3v+9J+G/H/mTe5hLeK7pLsvj7OclW6NLcwFBCZvTMTWcyhtM=
        overwrite: true
        on:
          tags: true
